### ISSUE TITLE
bad voltage regulator

### ISSUE THREAD

**Issue by nestorayuso** [will127534/LoRa-concentrator#1]
Hi, 

I see in your schematic you are using a XC6204 voltage regulators for 1.8 and 3.3 outputs from a 5v source.
This regulator has only 150mA max output current. This is insufficient.

SX1301 need 550mA typ, 750mA max @ 1.8v and 5mA typ, 10mA max @ 3.3v.

Even if you put a bigger LDO with 1A or more, the LDO will get very very hot, it will dissipate (5-1.8)*0.55= 1.76W of energy in hot.
I recommend to use a (step-down, DCDC converter...) switching regulator not linear regulator.

**Comment by will127534** [comment]
Hi nestorayuso,
Thanks for pointing out the problem.
XC6204 is actually just for general SOT-23 LDO package, I solder RT9193-18PB for 1.8v and SPX3819M5-L-3.3 for 3.3v.

But you are right, it is insufficient for SX1301, I'll change the 1.8v power rail design to step-down next version. 

Thanks for the comment.

**Comment by hallard** [comment]
For testing may be you can use dual output DC/DC step down like that, 
http://www.ebay.com/itm/DC-DC-Buck-Converter-Step-Down-Module-Power-Supply-1-5v-1-8v-3-3v-2A-Dual-Output-/262539347063

Not sure of quality but may be testing worth it.

**Comment by will127534** [comment]
Hi hallard,
thanks for the advice, maybe I'll look for that IC, looks very nice (2-in-1 chip)
I'm using Lab power supply for testing though.
![14163695_1187392487990796_2105983536_o](https://cloud.githubusercontent.com/assets/6110733/18189552/778b78e2-70ee-11e6-9d6c-43bde502b46e.jpg)
well I guess that SX1301 is dead, 1.8V rail only output 80mA, nowhere near the 700mA

This is the Log of util_pkt_logger:

lgw_connect:524: INFO: no FPGA detected or version not supported (v0)
Note: success connecting the concentrator
setup_sx125x:495: Note: SX125x #0 version register returned 0x11
setup_sx125x:500: Note: SX125x #0 clock output enabled
setup_sx125x:557: Note: SX125x #0 PLL start (attempt 1)
setup_sx125x:557: Note: SX125x #0 PLL start (attempt 2)
setup_sx125x:557: Note: SX125x #0 PLL start (attempt 3)
setup_sx125x:557: Note: SX125x #0 PLL start (attempt 4)
setup_sx125x:557: Note: SX125x #0 PLL start (attempt 5)
ERROR: FAIL TO LOCK PLL
setup_sx125x:495: Note: SX125x #1 version register returned 0x00
setup_sx125x:503: Note: SX125x #1 clock output disabled
setup_sx125x:557: Note: SX125x #1 PLL start (attempt 1)
setup_sx125x:557: Note: SX125x #1 PLL start (attempt 2)
setup_sx125x:557: Note: SX125x #1 PLL start (attempt 3)
setup_sx125x:557: Note: SX125x #1 PLL start (attempt 4)
setup_sx125x:557: Note: SX125x #1 PLL start (attempt 5)
ERROR: FAIL TO LOCK PLL
ERROR: Version of calibration firmware not expected, actual:177 expected:2
loragw_pkt_logger: ERROR: failed to start the concentrator

**Comment by nestorayuso** [comment]
Any progress?

550mA is when SX1301 is full running (8 MultiSF + LoRa + FSK receivers enabled), until not enabled 80mA can be a good value.

About PLL lock, 
do you have the 133MHz oscilator running?
do you have the 32MHz oscillator running and routed to both sx1255 radios?
which one of the sx1255 radios provides clock back to the SX1301?
is sx1301 configured to receive clock source from that radio?

**Comment by will127534** [comment]
133Mhz and 32Mhz are both running, I can see both osc are working, alsothe 32Mhz output from SX1255 to SX1301, seems OK
Not sure for the 133Mhz osc though, I'm using LVCMOS/LVTTL compatible osc.
32Mhz is for both SX1255, and I connected Radio A's 32Mhz out to SX1301.

**Comment by yuqian08** [comment]
Hi Will, this is very interesting board, we are working on design air quality sensors project based on Lora, but we doing the node with Microchip RN2903/2483, and have some productions released, maybe we can have some corporation in future :) 
I have a question, where you got those SX1301 documents and chips? from Semtech? thank you.

**Comment by will127534** [comment]
Hi yuqian08 ,
I just noticed that Semtech release the full datasheet for SX1301 and SX1308.

**Comment by will127534** [comment]
I've change 1.8V power reg to step-down, problem seems to be solved.
So closing this issue, thanks nestorayuso for pointing out this issue.
