### ISSUE TITLE
BOM and 868 mhz

### ISSUE THREAD

**Issue by krispstack** [will127534/LoRa-concentrator#13]
Hi Congrats and thanks for making it open source.

1. Can you please share the BOM file (bill of materials)
 
2. Please update LoRa-concentrator/Version2/RPI/SCH.pdf some of the labels of components are overlapped

3. What is the procedure to change it to 868 mhz

**Comment by apparell** [comment]
To change the operational frequency you have to adapt passive RF components and SAW filter from the radio frequency front end. Ther's lot of resources on the web about sizing RF matching network also.
Regards!

**Comment by apparell** [comment]
When Will will (WWW :D) publish the V3, I can help you to make 868 version. enjoy and happy open project!

**Comment by will127534** [comment]
Hi @karthirockz,
1.BOM file is uploaded.
2.Sch for V2 will update and upload later with V3
3.For 868Mhz, there are some parts needs to change,

- C26 to 56pF
- L3 to 56pF
- Saw filter need to replace with B39871B3717U410

Hi @apparell,  I might able to build 868Mhz version next time , just need to change a couple of SAW filter and Low pass filter on V3 board  :D

**Comment by apparell** [comment]
Hi @will127534 thanks for reply, I very appreciate your work! I'm sure you're able to make 868 version, no doubt. My effort is to empower community and collaboration

**Comment by clodpi** [comment]
@will127534 thanks, waiting for your 868 version

**Comment by krispstack** [comment]
@will127534 thanks, waiting for your 868 version

**Comment by davidfungf** [comment]
Hi @will127534 , waiting for your 868 version too. Thanks.

**Comment by gadLinux** [comment]
Me too. I suppose it's not as easy as change the parts you told above
