### ISSUE TITLE
Compatiblity with RPI3-MODBP-POE?

### ISSUE THREAD

**Issue by mweinelt** [will127534/LoRa-concentrator#15]
An interesting deployment is together with PoE (802.3af) through the official PoE Hat for the RPi 3 B+. Is this board compatible with that Hat?

Awesome project, eagerly awaiting an 868 model.

**Comment by will127534** [comment]
Guess who delay the manufacture for it.😄 
After they release PI 3B+and POE hat,I did changed the layout to stack POE hat on it.
