### ISSUE TITLE
Combining RX paths

### ISSUE THREAD

**Issue by amateusz** [will127534/LoRa-concentrator#17]
I'm not a RF design expert, but shouldn't RF RX paths (N$49 at your schematic for v3) be merged using some impedance matching ? Integrated [resistor divider](http://www.radio-electronics.com/info/rf-technology-design/coupler-combiner-splitter/rf-resistive-splitter-combiner-divider.php) (losses >= 6dB) or Wilkinson divider (losses >= 3dB). They cost pennies (~$0.3).

**Comment by will127534** [comment]
There is two inductor L1 and L2 and two Cap C22 with C20 for impedance matching.
So it is basically doing what resistive splitter is doing.
