### ISSUE TITLE
433Mhz和470Mhz频率，需要做哪些改进？

### ISSUE THREAD

**Issue by komoya** [will127534/LoRa-concentrator#20]
你好!
433Mhz 和470Mhz，除了把SX1257换成SX1255，还需要对哪些元件进行更换呢？  麻烦指教。

**Comment by will127534** [comment]
還有Balan要換成433Mhz的版本，PA和LNA的周邊匹配也要換一下，不過應該都有在PA/LNA的Datasheet
另外還有三個SAW filter+Low Pass Filter要換...
打字打到這邊我覺得基本上RF Frontend就只有IC沒換，其他都要...

**Comment by komoya** [comment]
谢谢您！  看来这个过程挺麻烦的。由于大陆不能用868和915的频率，只能用433， 有不少功课要做才能用上433Mhz
