### ISSUE TITLE
GPS coordinates

### ISSUE THREAD

**Issue by Brat0x2** [will127534/LoRa-concentrator#23]
@will127534 Hi!
I use GPS on the board version 3 with external antenna.
I see log messages:
`### [GPS] ###`
`# Valid time reference (age: 0 sec)`
`# no valid GPS coordinates available yet`
`##### END #####`
There is no valid coordinates for a long time. Why I didn't see them at all?

**Comment by will127534** [comment]
Hi @Brat0x2 
It seems GPS cannot fetch enough signal for solving the location (but still able to output time reference)
Can you confirm the GPS antenna can get a good reception?

Also you can use
`screen /dev/serial0 9600`  
to see the NEMA output from GPS, which have some info about the signal strength.

**Comment by Brat0x2** [comment]
@will127534 
![2018-07-17 20 14 44](https://user-images.githubusercontent.com/41232434/42826593-3af2ef02-89fe-11e8-95ab-d2457140d40f.png)

**Comment by will127534** [comment]
Yeah... It seems gps only locked  1 sat, where did you put the antenna?

**Comment by Brat0x2** [comment]
@will127534 Simple external antenna with 2 meters cable, on the window to the North.

**Comment by will127534** [comment]
It is active or passive antenna? 
if active, 5V or 3.3V?
The GPS Antenna port will output 3.3V to active antenna, so if you were using 5v active antenna,
it may cause the problem.

**Comment by Brat0x2** [comment]
@will127534 It is active GPS antenna, 2.7...5.0V

**Comment by will127534** [comment]
hmm.... can you put the antenna outdoor?

**Comment by Brat0x2** [comment]
There is no possibility now. I'll try as I can. Thanks for your help!

**Comment by heitorPB** [comment]
@Brat0x2 did you manage to solve this problem? I'm curious about it

**Comment by Brat0x2** [comment]
@heitorPB the problem has been solved. GPS depends on our local weather.
