### ISSUE TITLE
Frequency Plan 

### ISSUE THREAD

**Issue by hssounamed** [will127534/LoRa-concentrator#24]
hi will
when i bot the SX1308 Raspberry Pi Lora Gateway i have chosen the 868 MHz, i wanted to ask if by simple changing the Antenna to 915 Mhz will it be possible to use it as a Lora concentrator with a frequency plan of 915 MHz after configuring the global_conf files to 915 MHz.

if that's not possible you mentioned that the difference between the 868 model and the 915 model is simply 4 filters that we need to change, so is it possible to share the BOM file for the 868 MHz.
thank you have a great week.

**Comment by will127534** [comment]
Well... You can't.
There's four filter, three SAW Bandpass filter and a Low pass Filter,
So you have to change these filter:
U$8,U$4,U$9 : B39871B3717U410
U$6: 0868LP15A020
