### ISSUE TITLE
Capacitator values

### ISSUE THREAD

**Issue by deep470** [will127534/LoRa-concentrator#25]
Capacitators have voltage ratings, e.g. 5v, 10v, 25v, 50v.*

Which one do you recommend? Is 16v enough or better 25v to be sure?

Also: M15 (CAP-0402) has a value of 1K? Is that a special capacitor? 

1nF = 1000pF so M5, M17 and C19, C34 are the same, right?
C3 is the same as C1, C23, C24, C35?

Sorry, my electronics knowledge hasn't been used for decades.
Thank you for your great work!

**Comment by will127534** [comment]
So I normally double the voltage it handles,
for 3.3V rail => 10V or 6.3V
     1.8V => 6.3V
     5V => 10V
For the NP0 on the RF path and other small caps, their voltage rating is more then enough.

For M15, the package/sch name may cause some confusion, it is a 1K resistor, the M prefix is for impendence, so the component might be L,R or C, depends on the frequency needed.

M5,M17 should be 1500pF not 1000pF, so it is different then C19/C34
And C3 is the same as C1, C23, C24, C35

Thank you for the compliment! 👍
