### ISSUE TITLE
Using LoRa-concentrator V2 on spi 0.1

### ISSUE THREAD

**Issue by hamersin** [will127534/LoRa-concentrator#27]
JP1 allows selecting between SPI 0.0 and SPI 0.1. If I wanted to use SPI 0.1, what do I have to update to have the raspberry PI see the concentrator?

**Comment by will127534** [comment]
You will need to change /libloragw/src/loragw_spi.native.c line 57 
from /dev/spidev0.0 to /dev/spidev0.1
then recompile again.

**Comment by hamersin** [comment]
Thank worked - Thanks
