### ISSUE TITLE
One of sx1257 has very low RSSI

### ISSUE THREAD

**Issue by Brat0x2** [will127534/LoRa-concentrator#28]
I've got the LoRa-concentrator (the board version 3), EU868 configuration.
My LoRaWAN-mote sends messages, radio0 (ch0, ch1, ch2) receives them with RSSI -27, but radio1 (ch3, ch4, ch5, ch6, ch7) receives them corrupted only on ch5 with RSSI -111.
Thus only 3 from 10 messages reaches my server.
Is it a hardware problem? Maybe the board is damaged?

**Comment by will127534** [comment]
Yes, it seems to be a problem of the receiver,
and it seems that Radio B has a problem receiving the data...
Please contact me via tindle to send a replacement.

**Comment by will127534** [comment]
Note: I think the problem is the SX1257 on Radio B.

**Comment by Brat0x2** [comment]
@will127534 ok, thanks
