### ISSUE TITLE
Concentrator failed to start error  

### ISSUE THREAD

**Issue by kungfupizza** [will127534/LoRa-concentrator#33]
Hi,
I am having this error as shown below from a long time. It got solved once when a good power supply was provided but having it again. I always do the reset as told.
![GatewayError](https://user-images.githubusercontent.com/46355685/57751768-10a0b000-76e7-11e9-90c4-25a3547ea566.jpg)

**Comment by navinyate** [comment]
What is amps which u supplying to gateway. It should be atleast 2A

**Comment by navinyate** [comment]
And check if there are any loose wires.

**Comment by himitu23** [comment]
I also have this problem. I have searched several solution on some QAs, however I couldn't solve.

**Comment by navinyate** [comment]
what kind of problem.

**Comment by will127534** [comment]
LoRa Gateway is pretty sensitive to the power supply (normally talking to peak power consumption)
So make sure the power supply is working Ok.

**Comment by navinyate** [comment]
Which is gateway ur using

**Comment by himitu23** [comment]
> LoRa Gateway is pretty sensitive to the power supply (normally talking to peak power consumption)
> So make sure the power supply is working Ok.

OK, Thanks, I will try to use 2.5A supply
