### ISSUE TITLE
About the value of Resistance, capacitance, inductance

### ISSUE THREAD

**Issue by hyklkd** [will127534/LoRa-concentrator#7]
Hello, I have download your project and found that I can't get the value of Resistance, capacitance, inductance.Could you please show me you BOM?Thank you!

**Comment by will127534** [comment]
I'm currently choosing the values for PCBA, so I'll push version 2.1 later, maybe before the end of the month.

**Comment by will127534** [comment]
Values for 915Mhz are up!
