### ISSUE TITLE
Values

### ISSUE THREAD

**Issue by Hoel** [will127534/LoRa-concentrator#8]
Hi, i am interested in such concentrator for long range temperature humidity measurements (SHT21), i notice all values are removed, any chance you update the file or follow b email?
Thank you.

**Comment by will127534** [comment]
Hi hoel,
I'm currently choosing the values for PCBA, so I'll push version 2.1 later, maybe before the end of the month.

**Comment by will127534** [comment]
Values for 915Mhz are up!
