### ISSUE TITLE
great project！

### ISSUE THREAD

**Issue by colorado666** [will127534/LoRa-concentrator#9]
Great project, Merge the gateway with Raspberry pi is a good idea.
Is NDA going to be a problem?And what's the progress and roadmap?

**Comment by will127534** [comment]
Thanks!
I didn't signed any NDA, so its not going to be a problem IMAO.
Currently I'm building a version for RPI, with 2xSX125x and some SAW filter.
Testing is fine, and I just sended out to PCBA factory, maybe sold some unit on tindle later this year.
The newer version sch&layout will upload later this month.
